### ISSUE TITLE
Home Page Content

### ISSUE THREAD

**Issue by whereswaldon** [golangestonia/protoype-gioui.org#2]
# Demo

Kitchen Example Here

# Get Started

First you'll need to install Gio's dependencies. Gio is designed to work with very few dependencies. It depends only on the platform libraries for window management, input and GPU drawing.

- [Linux](https://gioui.org/doc/install#linux)
- [macOS, iOS, tvOS](https://gioui.org/doc/install#apple)
- [Windows](https://gioui.org/doc/install#windows)
- [Android](https://gioui.org/doc/install#android)
- [WebAssembly](https://gioui.org/doc/install#wasm)

Gio supports the latest released version of [Go](https://golang.org/dl) in module mode. Earlier versions of Go and GOPATH mode might work, but no effort is made to keep them working.

Once you have the dependencies, check out our [Guides](https;//gioui.org/doc/guides) to get started. If you want to build a working app quickly, jump straight to [Jon Egil Strand's Tutorials](https://jonegil.github.io/gui-with-gio/).

# Showcase

- [godcr](https://github.com/planetdecred/godcr): cross-platform desktop wallet for the [Decred](https://decred.org/) cryptocurrency
- [sprig](client for the Arbor chat system): client for the [Arbor Chat system](https;//arbor.chat)
- [Tailscale](https://github.com/tailscale/tailscale-android): a [Tailscale](https://tailscale.com/) Android client
- [Protonet](https://github.com/mearaj/protonet): peer-to-peer chat application
- [Wormhole William](https://github.com/psanford/wormhole-william-mobile): end-to-end encrypted file transfer application using the [Magic Wormhole](https://github.com/magic-wormhole/magic-wormhole-protocols) protocol
- [Sointu](https://github.com/vsariola/sointu/): modular software synthesizer to easily produce music for 4k intros
- [Photon](https://gitlab.com/microo8/photon): fast RSS reader as light as a photon

# Why?

Gio enables Go developers to build efficient, fluid, and portable GUIs across all major platforms. It combines bleeding-edge 2D graphics technology with the flexibility of the immediate mode graphics paradigm to create a compelling and consistent foundation for application development.

Gio programs run on all the major platforms: iOS/tvOS, Android, Linux (Wayland/X11), macOS, Windows, FreeBSD, OpenBSD, and experimental support for browsers (Webassembly/WebGL). There is a [unikernel port](https://eliasnaur.com/unik) for running Gio programs in virtual machines.

Gio includes an efficient vector renderer based on the [Pathfinder project](https://github.com/servo/pathfinder), implemented on OpenGL ES and Direct3D 11, and is migrating towards an even more efficient compute-shader-based renderer built atop [`piet-gpu`](https://github.com/linebender/piet-gpu). Text and other shapes are rendered using only their outlines without baking them into texture images, to support efficient animations, transformed drawing and pixel resolution independence.

# Sponsors

Gio development is funded by sponsorships. If you find Gio useful, please consider [sponsoring the project on OpenCollective](https://opencollective.com/gioui) or one or more of its developers directly.

Our current sponsors include:

<DECRED INFO HERE>

**Comment by egonelbre** [comment]
The content has been updated.
