### ISSUE TITLE
Community Page Content

### ISSUE THREAD

**Issue by whereswaldon** [golangestonia/protoype-gioui.org#3]
Gio's community is distributed all across the globe, and can be found on several platforms.

## Sourcehut

Our primary development platform is [sourcehut](https://sourcehut.org).

- [Gio sr.ht project home page](https://sr.ht/~eliasnaur/gio/)
- [Issue Tracker](https://todo.sr.ht/~eliasnaur/gio)
- Mailing Lists:
    - [Discussion](https://lists.sr.ht/~eliasnaur/gio)
    - [Patches](https://lists.sr.ht/~eliasnaur/gio-patches)
- [Contributing](https://gioui.org/doc/contribute)
- [Why sr.ht?](https://gioui.org/doc/faq#why-srht)

## Slack

You can find some of our community in the `#gioui` channel of the [`https://gophers.slack.com`](https://invite.slack.golangbridge.org/) workspace.

**Comment by egonelbre** [comment]
The content has been updated.
